---
  - name: apt update
    apt:
      update_cache: yes
    tags: update
  
  - name: apt dist-upgrade
    apt:
      upgrade: dist
    tags: update
  
  - name: set ip
    shell: bbb-conf --setip {{ inventory_hostname }}
    tags: update

  - name: set secret
    shell: bbb-conf --setsecret {{ bbb_secret }}
    tags: set_secret
  
  - name: register bbb
    shell: /root/register-bbb.sh bbb.messenger.schule {{ scalelite_prefix }} {{ ssh_key }}
    tags: update, set_secret

  - name: replace turn-stun-servers.xml
    copy:
      src: turn-stun-servers.xml
      dest: /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
      owner: bigbluebutton
      group: bigbluebutton
      mode: '0644'
    tags: turn_server
  
  - name: restart bbb
    shell: bbb-conf --restart
    tags: turn_server, set_secret

